config/routes.rb
MailchimpExample::Application.routes.draw do

  devise_for :users

  namespace :home, path: '/' do
    post :subscribe
  end

  root :controller => :application, :action => :welcome

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def welcome

  end
end

app/controllers/home_controller.rb
require "subscribe_to_newsletter"

class HomeController < ApplicationController
  def subscribe
    begin
      SubscribeToNewsletter.new.run(params)

      flash[:notice] = "You successfully subscribed to the Newsletter!"
    rescue Gibbon::MailChimpError => e
      flash[:alert] = e.message
    end
    redirect_to root_path
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_controller_helper.rb
module HomeControllerHelper
end

app/views/application/welcome.html.erb
<h1>Welcome to my app</h1>

<p>Subscribe to the Newsletter</p>

<%= form_tag(home_subscribe_path) do %>
  <div class="form-group">
    <%= text_field_tag :first_name, '', placeholder: 'First Name', class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= text_field_tag :last_name, '', placeholder: 'Last Name', class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= email_field_tag :email, '', placeholder: 'Email', class: 'form-control' %> 
  </div>
  <div class="form-group">
    <%= submit_tag "Subscribe", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Newsletter App</a>
    </div>
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails App Example</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "layouts/navbar"%>
<div class="container">
  <% if flash[:notice] || flash[:alert] %>
    <div class="alert alert-<%=flash[:notice] ? 'info' : 'danger'%> alert-dismissible">
      <button class="close" data-dismiss="alert">&times;</button>
      <p><%= flash[:notice] || flash[:alert] %></p>
    </div>
  <% end %>

  <%= yield %>
  
</div>

</body>
</html>